from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(781, 600)
        MainWindow.setFixedSize(781, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 241, 251))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 91, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 91, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 210, 91, 16))
        self.label_7.setObjectName("label_7")
        self.t_cold_wat = QtWidgets.QLineEdit(self.groupBox)
        self.t_cold_wat.setGeometry(QtCore.QRect(110, 30, 113, 21))
        self.t_cold_wat.setObjectName("t_cold_wat")
        self.t_hot_wat = QtWidgets.QLineEdit(self.groupBox)
        self.t_hot_wat.setGeometry(QtCore.QRect(110, 60, 113, 21))
        self.t_hot_wat.setObjectName("t_hot_wat")
        self.t_drin_wat = QtWidgets.QLineEdit(self.groupBox)
        self.t_drin_wat.setGeometry(QtCore.QRect(110, 90, 113, 21))
        self.t_drin_wat.setObjectName("t_drin_wat")
        self.t_t1 = QtWidgets.QLineEdit(self.groupBox)
        self.t_t1.setGeometry(QtCore.QRect(110, 120, 113, 21))
        self.t_t1.setObjectName("t_t1")
        self.t_t2 = QtWidgets.QLineEdit(self.groupBox)
        self.t_t2.setGeometry(QtCore.QRect(110, 150, 113, 21))
        self.t_t2.setObjectName("t_t2")
        self.t_t3 = QtWidgets.QLineEdit(self.groupBox)
        self.t_t3.setGeometry(QtCore.QRect(110, 180, 113, 21))
        self.t_t3.setObjectName("t_t3")
        self.t_wifi = QtWidgets.QLineEdit(self.groupBox)
        self.t_wifi.setGeometry(QtCore.QRect(110, 210, 113, 21))
        self.t_wifi.setObjectName("t_wifi")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(260, 10, 241, 251))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(10, 150, 91, 16))
        self.label_13.setObjectName("label_13")
        self.s_cold_wat = QtWidgets.QLineEdit(self.groupBox_2)
        self.s_cold_wat.setGeometry(QtCore.QRect(110, 30, 113, 21))
        self.s_cold_wat.setObjectName("s_cold_wat")
        self.s_hot_wat = QtWidgets.QLineEdit(self.groupBox_2)
        self.s_hot_wat.setGeometry(QtCore.QRect(110, 60, 113, 21))
        self.s_hot_wat.setObjectName("s_hot_wat")
        self.s_t1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.s_t1.setGeometry(QtCore.QRect(110, 90, 113, 21))
        self.s_t1.setObjectName("s_t1")
        self.s_t2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.s_t2.setGeometry(QtCore.QRect(110, 120, 113, 21))
        self.s_t2.setObjectName("s_t2")
        self.s_t3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.s_t3.setGeometry(QtCore.QRect(110, 150, 113, 21))
        self.s_t3.setObjectName("s_t3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(520, 10, 241, 251))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label_10.setObjectName("label_10")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(10, 150, 91, 16))
        self.label_17.setObjectName("label_17")
        self.n_cold_wat = QtWidgets.QLineEdit(self.groupBox_3)
        self.n_cold_wat.setGeometry(QtCore.QRect(110, 30, 113, 21))
        self.n_cold_wat.setObjectName("n_cold_wat")
        self.n_hot_wat = QtWidgets.QLineEdit(self.groupBox_3)
        self.n_hot_wat.setGeometry(QtCore.QRect(110, 60, 113, 21))
        self.n_hot_wat.setObjectName("n_hot_wat")
        self.n_t1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.n_t1.setGeometry(QtCore.QRect(110, 90, 113, 21))
        self.n_t1.setObjectName("n_t1")
        self.n_t2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.n_t2.setGeometry(QtCore.QRect(110, 120, 113, 21))
        self.n_t2.setObjectName("n_t2")
        self.n_t3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.n_t3.setGeometry(QtCore.QRect(110, 150, 113, 21))
        self.n_t3.setObjectName("n_t3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 260, 511, 291))
        self.groupBox_4.setObjectName("groupBox_4")
        self.table = QtWidgets.QTableWidget(self.groupBox_4)
        self.table.setGeometry(QtCore.QRect(10, 30, 491, 251))
        self.table.setRowCount(8)
        self.table.setColumnCount(2)
        self.table.setObjectName("table")
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setDefaultSectionSize(230)
        self.table.horizontalHeader().setMinimumSectionSize(19)
        self.calc_button = QtWidgets.QPushButton(self.centralwidget)
        self.calc_button.setGeometry(QtCore.QRect(570, 321, 161, 51))
        self.calc_button.setObjectName("calc_button")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(570, 440, 161, 51))
        self.save_button.setObjectName("save_button")
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(570, 380, 161, 51))
        self.reset_button.setObjectName("reset_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 781, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Flat Utilities Calculator 1.5"))
        self.groupBox.setTitle(_translate("MainWindow", "Tariffs"))
        self.label.setText(_translate("MainWindow", "Cold water"))
        self.label_2.setText(_translate("MainWindow", "Hot water"))
        self.label_3.setText(_translate("MainWindow", "Drinage water"))
        self.label_4.setText(_translate("MainWindow", "T1"))
        self.label_5.setText(_translate("MainWindow", "T2"))
        self.label_6.setText(_translate("MainWindow", "T3"))
        self.label_7.setText(_translate("MainWindow", "Wi-fi"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Start indicators"))
        self.label_8.setText(_translate("MainWindow", "Cold water"))
        self.label_9.setText(_translate("MainWindow", "Hot water"))
        self.label_11.setText(_translate("MainWindow", "T1"))
        self.label_12.setText(_translate("MainWindow", "T2"))
        self.label_13.setText(_translate("MainWindow", "T3"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Current indicators"))
        self.label_10.setText(_translate("MainWindow", "Cold water"))
        self.label_14.setText(_translate("MainWindow", "Hot water"))
        self.label_15.setText(_translate("MainWindow", "T1"))
        self.label_16.setText(_translate("MainWindow", "T2"))
        self.label_17.setText(_translate("MainWindow", "T3"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Result"))
        self.calc_button.setText(_translate("MainWindow", "Calculate"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.reset_button.setText(_translate("MainWindow", "Reset"))
